<center>
<table style="border:none">
    <tr style="border:none">
    <th style="border:none">
        <a  href='https://colab.research.google.com/github/AmirMardan/ml_course/blob/main/2_numpy/0_intro_to_numpy.ipynb'><img src='https://colab.research.google.com/assets/colab-badge.svg'></a>
    </th>
    <th style="border:none">
        <a  href='https://github1s.com/AmirMardan/ml_course/blob/main/2_numpy/0_intro_to_numpy.ipynb'><img src='../imgs/open_vscode.svg' height=20px width=115px></a>
    </th>
    </tr>
</table>
</center>


This notebook is created by <a href='https://amirmardan.github.io'> Amir Mardan</a>. For any feedback or suggestion, please contact me via my <a href="mailto:mardan.amir.h@gmail.com">email</a>, (mardan.amir.h@gmail.com).



<center>
<img src='img/numpy.png' width='300px'>
</center>

<a name='top'></a>
# Introducción a  NumPy

Este cuaderno cubrirá los siguientes temas:
- [Introducción](#introduction)
- [NumPy vs lista](#numpy_list)
- [1. Creando un array NumPy](#creating)
    - [Creando arrays desde listas](#creating_with_list)
    - [Arrays especiales](#special_array)
- [2. Atributos de arrays](#attributes_array)
- [3. Selección de datos](#data_election)
    - [Indexación de arrays](#indexing)
    - [Corte de arrays](#slicing)
    - [Vista vs copia de arrays](#view_copy)
    - [Selección condicional](#conditional)
- [4. Manipulación de arrays](#manipulation)
    - [Forma de un array](#shape)
    - [Uniendo arrays](#joining)
    - [División de arrays](#splitting)
- [5. Cálculo en arrays de NumPy](#computation)
- [6. Agregaciones](#aggregations)
    - [Suma](#summation)
    - [Mínimo y máximo](#min_max)
    - [Varianza y desviación estándar](#var_std)
    - [Media y mediana](#mean_median)
    - [Encontrar índice](#find_index)


<a name='introduction'></a>
## Introducción


NumPy es una biblioteca para trabajar con grandes matrices y arreglos multidimensionales. 
Fue creado por **Travis Oliphant**, lanzado por primera vez en 1995 como *Numeric* y cambió a *NumPy* en 2006.

<center><img src='./img/travis.jpeg' alt='tavis' width=300px></center>

El objeto de array en NumPy se llama `ndarray`


<a name='numpy_list'></a>
## NumPy vs list 


**Ventajas de usar matrices NumPy sobre listas de Python**

- Numpy ocupa menos memoria.
- Numpy es más rápido.
- Numpy tiene una mejor funcionalidad.

Vamos a comprobar si estas afirmaciones son ciertas. Pero primero, necesitamos indicarle a Python que queremos usar NumPy. Para hacerlo, importamos este paquete. Generalmente, un paquete de Python se importa al comienzo de un script de la siguiente manera:

```python
import numpy
```
Para mayor comodidad, Python nos permite elegir un alias para el módulo que importamos utilizando la palabra clave as:

```Python
 import numpy as np
    
```

In [14]:
# Import numpy 

import numpy as np

n = 1000

# Make an array of zeros
numpy_version = np.zeros(n)

list_version = list(numpy_version)

print(type(list_version), type(numpy_version))

<class 'list'> <class 'numpy.ndarray'>


<div class="alert alert-block alert-danger">
<b>Peligro:</b> ¡Ten en cuenta que la adición de dos listas causa concatenación!
</div>

In [15]:
def numpy_based():
    return  numpy_version + 5
    
    
def list_based():
    return [list_version[i] + 5 for i in range(len(list_version))]

In [16]:
%timeit list_based()
%timeit numpy_based()


247 µs ± 12.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.16 µs ± 137 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


En muchos materiales, vemos que se utiliza el ejemplo anterior para mostrar que NumPy es más rápido, pero la verdad es que la función `list_based` no está implementada correctamente. Escribámosla con `map()` como aprendimos en la introducción a Python.


In [17]:
def list_based():
    add = lambda a: a + 5
    return map(add, list_version)


%timeit list_based()
%timeit numpy_based()
print('Voila, list is faster now.')


229 ns ± 21.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.78 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
Voila, list is faster now.


In [18]:
# Let's check the size and values 

a = numpy_based()
b = list_based()

c = list(b)
print("They're equal!\nNumPy: ", a.shape, "\nlist: ", np.shape(c)) if [np.all(c == a)] else print('Wrong!') 


They're equal!
NumPy:  (1000,) 
list:  (1000,)


Pero sin duda, NumPy nos brinda más funcionalidad y los métodos de NumPy son más rápidos al utilizar matrices de NumPy.

In [19]:
def numpy_based():
    return np.mean(numpy_version)


def list_based():
    return np.mean(list_version)


In [20]:
%timeit list_based()
%timeit numpy_based()

50.8 µs ± 4.05 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
7.7 µs ± 810 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


<a name='creating'></a>
## 1 . Creando un array de numpy


`numpy.array` puede ser utilizado para crear un tensor

<center><img src='img/Tensor_01.webp' alt='tensor' width=400px></center>

In [21]:
# Create 0-D array

a = np.array(2)

print("a = ", a, "; shape: ", a.ndim)

a =  2 ; shape:  0


<a name='creating_with_list'></a>
### 1.1 Creando arrays a partir de listas



Podemos utilizar `np.array()` para crear un array a partir de listas de Python

```Python
np.array(list_name)
```

In [22]:
# Create 1-D 'float' array

np.array([1.0, 4.3, 8., 9])

array([1. , 4.3, 8. , 9. ])

We can use the parameter `dtype` to specify the type of data,

```Python
np.array(list_name, dtype=desired_type)
```

In [23]:
# Create 1-D 'int' array

np.array([1.0, 4., 8., 9], dtype=np.int32)

array([1, 4, 8, 9], dtype=int32)

In [24]:
# Create 2-D array

np.array([[1.0, 4., 8., 9],
          [2, 4, 1, 3]], dtype=np.float32)

array([[1., 4., 8., 9.],
       [2., 4., 1., 3.]], dtype=float32)

<a name='special_array'></a>
### 1.2 Arrays especiales


Es mejor utilizar métodos especiales en NumPy para matrices más grandes. Estas matrices especiales son:

- Matriz de todos ceros
- Matriz de todos unos
- Matriz identidad
- Matriz vacía
- Matriz llena
- Matriz aleatoria
- Matrices basadas en un rango dado

Por lo general, estas matrices se crean utilizando la siguiente sintaxis:

```python
np.array(shape=tupla_de_forma, dtype=tipo_de_dato)



In [25]:
# Creando un array de ceros

np.zeros(shape=(5, 2), dtype=np.float32)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [26]:
# Creando un array de ceros utilizando zero like

np.zeros_like(np.ones(shape=(5, 2), dtype=np.float32))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

Para facilitarlo, podemos permitir que NumPy decida el tipo de datos para el resto de este cuaderno.

In [27]:
# CCreando un array de unos

np.ones(shape=(5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
# Creando una matriz identidad
# Note: np.eye no toma el shape como argumento

np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [29]:
# Creando un array vacio

np.empty(shape=(5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
# Creando un array vacio utilizando empty like

np.empty_like(np.zeros((5, 2)))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
# Creando una matriz de números aleatorios (distribución normal)

np.random.normal(loc=0, scale=1, size=(5,2))

array([[ 0.17062204, -0.21492141],
       [ 0.7155442 ,  0.39635688],
       [ 0.59504293, -0.17271905],
       [-0.22654837, -0.18984   ],
       [-0.02881549, -0.45848519]])

In [32]:
#Creando una matriz de números aleatorios (distribución uniforme)

np.random.random((5, 2))

array([[0.75215207, 0.34983341],
       [0.64344263, 0.58815099],
       [0.26404833, 0.55362301],
       [0.31052892, 0.47518967],
       [0.82592835, 0.15964281]])

<hr>
<div>
<span style="color:#151D3B; font-weight:bold">Pregunta: 🤔</span><p>
Genera una matriz con forma de [10, 10] y valores entre 5 y 7
</div>
<hr>

In [33]:
# Respuesta



In [34]:
# creando un array de numeros aleatorios

np.random.rand(5, 2)

array([[0.70682547, 0.59455001],
       [0.65518301, 0.67877073],
       [0.95691894, 0.74693485],
       [0.04928195, 0.21861677],
       [0.7196692 , 0.18226771]])

In [35]:
# Creando un array de numeros enteros al azar

np.random.randint(low=1, high=5, size=(5, 2))

array([[1, 4],
       [1, 1],
       [2, 4],
       [4, 1],
       [1, 1]])

In [36]:
# Creando un array en un rango especifico

np.arange(start=1, stop=4, step=0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9])

In [37]:
# Creating un array en un rango

np.linspace(start=1, stop=4, num=10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [38]:
# Creating un array en un rango

np.logspace(start=1, stop=4, num=10)

array([   10.        ,    21.5443469 ,    46.41588834,   100.        ,
         215.443469  ,   464.15888336,  1000.        ,  2154.43469003,
        4641.58883361, 10000.        ])

<a name='attributes_array'></a>
## 2. Atributos de los arrays


Utilizamos atributos para determinar algunas propiedades de la matriz, como la forma, el tamaño, etc.

In [39]:
x = np.random.randint(14, size=(4, 3))

print(x)

[[11  6  6]
 [ 8  5  4]
 [ 5  1 10]
 [13  3  2]]


In [40]:
print("Dimensión: ", x.ndim) 
print("Forma: ", x.shape) 
print("Tamaño: ", x.size) 
print("Ttipo: ", x.dtype)
print("Tamaño del elemento: ", x.itemsize, 'bytes')  # Size of each element
print("Tamaño del array: ", x.nbytes, 'bytes')  # Size of the array

Dimensión:  2
Forma:  (4, 3)
Tamaño:  12
Ttipo:  int64
Tamaño del elemento:  8 bytes
Tamaño del array:  96 bytes


<a name='data_election'></a>
## 3. Selección de data
 

***Indexing*** se utiliza para seleccionar un elemento individual de una matriz.

***Slicing*** se utiliza para seleccionar una parte de una matriz.


<a name='indexing'></a>
### 3.1 Indexación de arrays

Por favor nota que Python empieza a contar desde el `0`.

In [41]:
x_1d = np.random.random((6, 1))
x_1d

array([[0.26688969],
       [0.13066217],
       [0.08024198],
       [0.36686186],
       [0.34519473],
       [0.04152749]])

In [42]:
# Accede al primer elemento 

x_1d[0]

array([0.26688969])

In [43]:
# Access el último elemento 

x_1d[-1]

array([0.04152749])

In [44]:
x_2d = np.random.random((4, 5))
x_2d

array([[0.37453233, 0.58893994, 0.16378593, 0.63825367, 0.80099907],
       [0.88408157, 0.60317711, 0.25537868, 0.97010006, 0.17170573],
       [0.05004484, 0.33600363, 0.85743749, 0.82128264, 0.02675642],
       [0.17148475, 0.52313175, 0.45518595, 0.37649852, 0.48386728]])

In [45]:
x_2d[0, 0]

0.3745323281363119

In [46]:
x_2d[0][0]

0.3745323281363119

<hr>
<div>
<span style="color:#151D3B; font-weight:bold">Pregunta: 🤔</span><p>
¿Cuál sería el resultado de <code>x_2d[0, 0]</code>?
</div>
<hr>

In [47]:
# Rtta

<a name='slicing'></a>
### 3.2 Slicing de arrays 



Para realizar un slicing de una matriz unidimensional, utilizamos la siguiente sintaxis:

```Python
sliced = original[inicio:fin:paso]
```
Si no se da `paso`, se va a considerar como `1`


In [48]:
x_1d

array([[0.26688969],
       [0.13066217],
       [0.08024198],
       [0.36686186],
       [0.34519473],
       [0.04152749]])

In [49]:
# Especifica el inicio y el fin de la sección deseada por número

x_1d[1:4]

array([[0.13066217],
       [0.08024198],
       [0.36686186]])

<div class="alert alert-block alert-info">
<b>Consejo:</b> Ten en cuenta que el elemento 1 está incluido, pero ese no es el caso para el elemento 4.</div>

In [50]:
"""
Especifica el inicio o el fin de la sección deseada que 
corresponda al inicio o al final de la matriz.
"""

x_1d[1:]

array([[0.13066217],
       [0.08024198],
       [0.36686186],
       [0.34519473],
       [0.04152749]])

In [51]:
# Indexación con paso mayor que 1

x_1d[1::2]

array([[0.13066217],
       [0.36686186],
       [0.04152749]])

In [52]:
# Podemos invertir la matriz mediante la indexación.

x_1d[-1:0:-1]

array([[0.04152749],
       [0.34519473],
       [0.36686186],
       [0.08024198],
       [0.13066217]])

In [53]:
# Slicing en 2-D

x_2d[1:, 3:5]

array([[0.97010006, 0.17170573],
       [0.82128264, 0.02675642],
       [0.37649852, 0.48386728]])

<a name='view_copy'></a>
### 3.3 Array view vs copia

Una cosa extremadamente importante de saber es que los segmentos de una matriz devuelven *vistas* de los datos en lugar de *copias*. Esta es otra diferencia entre las matrices de NumPy y las listas de Python.


In [54]:
print(x_1d)

x_1d_sliced = x_1d[0]

x_1d_sliced *= 2

print("======== \n", x_1d)


[[0.26688969]
 [0.13066217]
 [0.08024198]
 [0.36686186]
 [0.34519473]
 [0.04152749]]
 [[0.53377937]
 [0.13066217]
 [0.08024198]
 [0.36686186]
 [0.34519473]
 [0.04152749]]


Para prevenir cualquier problema, debes usar el método `copy()`

In [55]:
print(x_1d)

x_1d_sliced = x_1d[0].copy()

x_1d_sliced *= 2

print("======== \n", x_1d)

[[0.53377937]
 [0.13066217]
 [0.08024198]
 [0.36686186]
 [0.34519473]
 [0.04152749]]
 [[0.53377937]
 [0.13066217]
 [0.08024198]
 [0.36686186]
 [0.34519473]
 [0.04152749]]


<a name='conditional'></a>
### 3.4 Selección condicional

Podemos usar una condición para seleccionar una parte de un arreglo.


In [56]:
x_1d

array([[0.53377937],
       [0.13066217],
       [0.08024198],
       [0.36686186],
       [0.34519473],
       [0.04152749]])

In [57]:
# Creemos una condicion

cond = x_1d > 0.7
cond

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [58]:
# Seleccionar los datos basados en la condición


x_1d[cond]

array([], dtype=float64)

In [59]:
# Vamos a crear una matriz 2-D


x_2d_int = np.random.randint(12, size=(5, 6))

x_2d_int

array([[ 9,  8,  4,  6,  0,  4],
       [ 8,  8,  1,  0,  5,  2],
       [11,  8,  5, 10,  5,  9],
       [ 4,  1,  9,  3,  2,  8],
       [ 5,  2,  1,  9,  1,  5]])

In [60]:
# Vamos a extraer los números pares


x_2d_int[x_2d_int % 2 == 0]

array([ 8,  4,  6,  0,  4,  8,  8,  0,  2,  8, 10,  4,  2,  8,  2])

<hr>
<div>
<span style="color:#151D3B; font-weight:bold">Pregunta: 🤔</span><p>
Usando indexación condicional, extrae los números en <code>x_2d_int</code> que son divisibles tanto por 2 como por 7.
</div>
<hr>


In [61]:
# Rtta



<a name='manipulation'></a>
## 4. Manipulación de arrays


La manipulación de datos es un paso importante en cualquier estudio.


<a name='shape'></a>
### 4.1 Forma del array


In [62]:
# Cremos algunos arrays

arr_1d = np.arange(10)
arr_2d = 5 * np.random.random((4, 5))


In [63]:
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr_2d

array([[1.32720813, 3.62144772, 0.6648468 , 4.05551839, 4.11306466],
       [0.9483566 , 3.98388102, 1.14724482, 2.50510148, 0.45639914],
       [4.97823222, 4.5248492 , 1.51973616, 1.42423003, 1.90788903],
       [2.7236325 , 2.28655278, 4.2860905 , 4.45252043, 3.07183026]])

In [65]:
# La forma de un arreglo se puede obtener de 2 maneras.


print(arr_1d.shape, np.shape(arr_1d))

(10,) (10,)


In [66]:
arr_2d.shape

(4, 5)

Podemos cambiar fácilmente la forma de un arreglo de NumPy.

```Python
array.reshape(filas, columnas)

np.reshape(array, newshape=(filas, columnas))


In [67]:
arr_2d.reshape(5, 4)

array([[1.32720813, 3.62144772, 0.6648468 , 4.05551839],
       [4.11306466, 0.9483566 , 3.98388102, 1.14724482],
       [2.50510148, 0.45639914, 4.97823222, 4.5248492 ],
       [1.51973616, 1.42423003, 1.90788903, 2.7236325 ],
       [2.28655278, 4.2860905 , 4.45252043, 3.07183026]])

In [68]:
np.reshape(arr_2d, newshape=(5, 4))

array([[1.32720813, 3.62144772, 0.6648468 , 4.05551839],
       [4.11306466, 0.9483566 , 3.98388102, 1.14724482],
       [2.50510148, 0.45639914, 4.97823222, 4.5248492 ],
       [1.51973616, 1.42423003, 1.90788903, 2.7236325 ],
       [2.28655278, 4.2860905 , 4.45252043, 3.07183026]])

In [69]:
# Podemos aplanar un arreglo utilizando el atributo `flatten`.

```python
array.flatten()


arr_2d.flatten()


SyntaxError: invalid syntax (3314245495.py, line 3)

<div class="alert alert-block alert-info">
<b>Consejo:</b> El método `reshape` no modifica el arreglo original, mientras que el método `resize` devuelve <code>None</code> y modifica el arreglo en su lugar.</div>



In [ ]:
print("Froma original: ", arr_2d.shape)

arr_2d.reshape(5, 4)

print("Forma luego de usar reshape: ", arr_2d.shape)

a = arr_2d.resize(5, 4)

print("Forma luego de utilizar resize: ", arr_2d.shape)


<span style='color:red; font-weight:bold;'>Nota:</span> El método <code>np.resize()</code> funciona de manera similar a <code>np.reshape()</code>.


In [ ]:
print("Forma original: ", arr_2d.shape)

np.reshape(arr_2d, (5, 4))

print("Forma luego de reshape: ", arr_2d.shape)

np.resize(arr_2d, (5, 4))

print("Forma luego de resize: ", arr_2d.shape)

<a name='joining'></a>
### 4.2 Haciendo join de arrays


In [ ]:
arr1 = np.array([[1, 2, 0, 1]])

arr2 = 6 * np.random.random((4, 4))

In [ ]:
# Chequea la forma
print('arr1: ', arr1.shape)
print('arr2: ', arr2.shape)

In [ ]:
# Haciendo join por filas

np.concatenate((arr2, arr1), axis=0)

For using `axis = 0`, we should have the same number of columns and for `axis = 1`, we should have the same number of rows.

In [ ]:
# haciendo join por columnas 
# `.T` realiza la transposición de un arreglo, al igual que `np.transpose()`.

np.concatenate((arr2, arr1.T), axis=1)

In [ ]:
# Joining by vstack which acts as using axis = 0

np.vstack((arr2, arr1))

In [ ]:
# Al unir mediante `vstack` se realiza una concatenación a lo largo del eje 0, equivalente a usar `axis=0`.


np.hstack((arr2, arr1.T))

In [ ]:
# Al unir mediante `column_stack` se realiza una concatenación a lo largo del eje 1, equivalente a usar `axis=1`.


np.column_stack((arr2, arr1.T))

<a name='splitting'></a>
### 4.3 Division de arrays 


El opuesto de concatenación es división.

`np.split`, `np.hsplit`, `np.vsplit`


In [ ]:
arr2

In [ ]:
# Dividiendo con el eje = 0

np.split(arr2, 2)

In [ ]:
# Dividiendo con eje = 1

np.array_split(arr2, 2, axis=1)

In [ ]:
# Utilizando hsplit / vsplit

np.hsplit(arr2, 2)

<a name='computation'></a>
## 5. Cálculos en arreglos de NumPy



Los cálculos en arreglos de NumPy pueden ser muy rápidos si utilizamos operadores *vectorizados* a través de *funciones universales*, **ufuncs**.


In [ ]:
# Creando dos arrays

arr1d_1 = np.arange(7)
arr1d_2 = np.linspace(9, 12, len(arr1d_1))


arr2d_1 = np.random.random((4, 5))
arr2d_2 = 4 + 6 * np.random.random((4, 5))

In [ ]:
#Adición de dos arrays (equivalente de arr1d_1 + arr1d_2)

np.add(arr2d_1, arr2d_2)

In [ ]:
#Resta de dos arrays(equivalent of arr1d_1 - arr1d_2)

np.subtract(arr2d_1, arr2d_2)

In [ ]:
# Multiplicación de dos arrays (equivalent of arr1d_1 * arr1d_2)

np.multiply(arr2d_1, arr2d_2)

In [ ]:
# División de dos arrays (equivalent of arr1d_1 + arr1d_2)

np.divide(arr2d_1, arr2d_2)

In [ ]:
# Logaritmo de un array

np.log10(arr2d_1)

In [ ]:
# Exponente de un array 
np.exp(arr2d_1)

In [ ]:
# Seno de un array

np.sin(arr2d_1)

In [ ]:
# Comparación para mayor, equivalente a `arr2d_1 > arr2d_2`


np.greater(arr2d_1, arr2d_2)

In [ ]:
# Comparison for greate, equivalent arr2d_1 < arr2d_2

np.less(arr2d_1, arr2d_2)

In [ ]:
# Encontrar el valor absoluto de un arreglo, equivalente a `np.absolute`

np.abs([2, -1, 9, -1.2])

<a name='aggregations'></a>
## 6. Agregaciones



Antes de realizar cualquier operación, es bueno tener estadísticas resumidas de los datos.


<a name='summation'></a>
###  6.1 Suma


In [ ]:
# Creemos un array 

arr1 = np.random.random((100, 100))


In [ ]:
# Suma de valores en un array 

np.sum(arr1)

In [ ]:
# Comparando con la función incorporada de Python


big_array = np.random.random(100000)

%timeit sum(big_array)
%timeit np.sum(big_array)

<a name='min_max'></a>
###  6.2 Mínimo y máximo 


In [ ]:
# Creemos un array

arr1 = np.random.random((6, 5))

In [ ]:
# Encontrando max a lo largo de las columnas

arr1.max(axis=0)

In [ ]:
# Encontrando max a lo largo de las filas
arr1.max(axis=1)

In [ ]:
# Encontrando min
arr1.min(axis=0)

In [ ]:
# Podemos usar `np.max` / `np.min` también.

np.max(arr1, axis=1)

<a name='var_std'></a>
### 6.3 Varianza y desviación estandar 


In [ ]:
# Creemos un array 

arr1 = np.random.random((6, 5))

In [ ]:
# Calculando la desviación estándar del arreglo.

np.std(arr1)

In [ ]:
arr1.std()

In [ ]:
# Vamos a verificar si la desviación estándar es igual a la raíz cuadrada de la varianza.

arr1.std() == np.sqrt(arr1.var())

In [ ]:
# Desviación estándar a lo largo de las filas.

arr1.std(axis=1)

In [ ]:
# varianza a lo largo de las columnas

arr1.var(axis=0)

<a name='mean_median'></a>
###  6.4 Media y mediana


In [ ]:
# Creemos un array

arr1 = np.random.random((6, 5))

In [ ]:
# Calulemos la media de un array

arr1.mean()

In [ ]:
# Calcular la media a lo largo de un eje.

arr1.mean(axis=1)

In [ ]:
# Calcular la media de todo el arreglo.

np.median(arr1)

<span style='color:red; font-weight:bold;'>Nota: </span> Un <code>ndarray</code> no tiene el método "median".

<a name='find_index'></a>
###  6.5 Encontrar indice 


In [ ]:
# Creemos un array

arr1 = np.random.random((6, 5))
arr1[3, 3] = 0
arr1

In [ ]:
# Encontremos el indice del maximo valor

arr1.argmax()

In [ ]:
# Encontremos el índice del mínimo valor

arr1.argmin()

In [ ]:
# Encontremos el índice de un valor específico

np.where(arr1 == 0)

### [AL PRINCIPIO ☝️](#top)
